### ISSUE TITLE
Feature Request: exposing scanning parameters in UI

### ISSUE THREAD

**Issue by interactivetech** [eospi/Object-Capture-UI#1]
Amazing work! To further improve your app, HelloPhotogrammetry has additional settings that are really valuable when 3D scanning. Exposing the following setting will help scanning and compare 3D scans under different settings:
* sample-overlap
* sample-ordering
* feature-sensitivity

Below is a copy of all the commandline arguments available from HelloPhotogrammetry. Thanks for all the amazing work!
```
USAGE: hello-photogrammetry <input-folder> <output-filename> [--detail <detail>] [--sample-overlap <sample-overlap>] [--sample-ordering <sample-ordering>] [--feature-sensitivity <feature-sensitivity>]

ARGUMENTS:
  <input-folder>          The local input file folder of images. 
  <output-filename>       Full path to the USDZ output file. 

OPTIONS:
  -l, --sample-overlap <sample-overlap>
                          sampleOverlap {normal, low}  It should be set to `low` if there is low overlap between images captured nearby in space. 
  -o, --sample-ordering <sample-ordering>
                          sampleOrdering {unordered, sequential}  Setting to sequential may speed up computation if images are captured in a spatially
                          sequential pattern. 
  -f, --feature-sensitivity <feature-sensitivity>
                          featureSensitivity {normal, high}  Set to high if the scanned object does not contain a lot of discernible structures, edges
                          or textures. 

```

**Comment by eospi** [comment]
Thank you so much for using Object Capture UI! I wanted to get the basic workflow working so people had something to try during WWDC week, and I will be releasing updates soon with more features, including the additional options you linked. I will keep the issue open until then and write back when it's ready. 😄

**Comment by eospi** [comment]
The new PhotoCatch is out now with full customization options!
