### ISSUE TITLE
Save Button

### ISSUE THREAD

**Issue by linesplitter91** [eospi/Object-Capture-UI#2]
I think the save button doesn't work right now 😊
Maybe a screenshot from my configuration will help you to fix it ^
<img width="698" alt="Bildschirmfoto 2021-06-12 um 21 18 36" src="https://user-images.githubusercontent.com/62568561/121787026-fb4b2800-cbc3-11eb-9fae-92aa37491db3.png">

**Comment by eospi** [comment]
Thank you for the info! If your graphics card has 4GB of VRAM, then the problem might be with your images. Please try my sample folder below and let me know if it works!

[Try the koala images](https://drive.google.com/drive/folders/1Aao22_poIP0TZ-zBDyfvjAQK1Lqg_DmN)

**Comment by eospi** [comment]
The new PhotoCatch version is out, so I'm going to close this issue for now. Let me know if you have any other questions!
