### ISSUE TITLE
App Crashes on Begin Reconstruction 

### ISSUE THREAD

**Issue by karthigeyan9900** [eospi/Object-Capture-UI#3]
Hi,
 I have been trying to use the app multiple times but constantly facing crashes once I on click on the the "Begin Reconstruction" button. 
Tried installing all the packages as well. But no help.

<img width="982" alt="Screenshot 2021-06-15 at 8 34 21 PM" src="https://user-images.githubusercontent.com/29111806/122077400-5590f680-ce19-11eb-8ed1-818df851cf21.png">

**Comment by eospi** [comment]
Hi! What are the specs on your Mac? Do they meet either of the requirements below?

- Any Apple Silicon Mac
- Intel Mac with 16GB of RAM + AMD Graphics Card with 4GB VRAM

**Comment by reysantana** [comment]
![image](https://user-images.githubusercontent.com/58710601/122091644-a3344180-cdce-11eb-99d2-0b622dc2d2c4.png)
HI @eospi , 
It crashes.
This is my spec...

**Comment by eospi** [comment]
Hi @reysantana,
Unfortunately your Mac is not compatible because Object Capture requires a dedicated AMD graphics card with 4GB of VRAM for an Intel Mac.

**Comment by karthigeyan9900** [comment]
It doesn't have an AMD GPU with 4GB VRAM. Is it a min requirement for the app or the Object capture in general ?

**Comment by eospi** [comment]
The GPU is a requirement for Object Capture in general. However, all Apple Silicon Macs work with the GPU inside the M1.

**Comment by karthigeyan9900** [comment]
Hi a quick help, which spec would you suggest for Object Capture.

13" Pro with M1 or 16" Pro with Dedicated 4GB AMD GPU ?

**Comment by eospi** [comment]
For performance, I'd go with the M1!
