### ISSUE TITLE
Hi a quick help, which spec would you suggest for Object Capture.

### ISSUE THREAD

**Issue by karthigeyan9900** [eospi/Object-Capture-UI#4]
Hi a quick help, which spec would you suggest for Object Capture.

13" Pro with M1 or 16" Pro with Dedicated 4GB AMD GPU ?

_Originally posted by @karthigeyan9900 in https://github.com/eospi/Object-Capture-UI/issues/3#issuecomment-862585924_

**Comment by eospi** [comment]
I'd suggest the M1 for performance and power efficiency. From qualitative tests, the M1 MacBook Air runs faster than my 16" Pro with no fan, and it barely heats up!

**Comment by karthigeyan9900** [comment]
Cool Ethan, Thanks for the help !
