### ISSUE TITLE
GPU compatibility

### ISSUE THREAD

**Issue by Echolink50** [eospi/Object-Capture-UI#5]
Will any intel and any 4GB AMD gpu work? Is a  R7 350x compatible with the object capture API? How about an i5 4590? Thanks

**Comment by pozzoq** [comment]
I have an intel Mac with i5 CPU and an e-GPU, the AMD 5500XT with 4 Gb of video ram. Photocatch arrives at 15% reconstruction and then the Mac freezes. Does it depend on the e-GPU? 

Many many thanks

**Comment by Echolink50** [comment]
> I have an intel Mac with i5 CPU and an e-GPU, the AMD 5500XT with 4 Gb of video ram. Photocatch arrives at 15% reconstruction and then the Mac freezes. Does it depend on the e-GPU?
> 
> Many many thanks

Wish i knew. I just grabbed an M1 Mac Mini for now. The Intel cpu and AMD gpu requirements seem very vague. If you have a real Mac the issue seems strange. Are you able to run Object Capture without photocatch? If you have a Hack it could be some of anything.

**Comment by eospi** [comment]
The basic requirements are a Mac with 16GB of RAM an AMD GPU with 4GB of VRAM, but generally a newer Mac within the last few years is required. I have not tested with an e-GPU, but any error message about GPU support means that the Mac is not compatible.

**Comment by pozzoq** [comment]
I have a real Mac, the 13 inches with intel 10th gent with G7 integrated graphics and a AMD Radeon 5500XT as e-GPU that the system recognizes seamlessly. What happens is that reaching the 15-16% of the process the Mac freezes and eventually after a few minutes shuts down. No error message whatsoever, unfortunately.

But indeed, tested with a M1 Mac it is pretty impressive in terms of quality and performance.

**Comment by Echolink50** [comment]
> I have a real Mac, the 13 inches with intel 10th gent with G7 integrated graphics and a AMD Radeon 5500XT as e-GPU that the system recognizes seamlessly. What happens is that reaching the 15-16% of the process the Mac freezes and eventually after a few minutes shuts down. No error message whatsoever, unfortunately.
> 
> But indeed, tested with a M1 Mac it is pretty impressive in terms of quality and performance.

Have you tried running object capture from the command line? Also, how many images are you trying to process?

If other people could post working working NON-M1 setups that would be helpful. Thanks

**Comment by eospi** [comment]
> I have a real Mac, the 13 inches with intel 10th gent with G7 integrated graphics and a AMD Radeon 5500XT as e-GPU that the system recognizes seamlessly. What happens is that reaching the 15-16% of the process the Mac freezes and eventually after a few minutes shuts down. No error message whatsoever, unfortunately.
> 
> But indeed, tested with a M1 Mac it is pretty impressive in terms of quality and performance.

Does your 13” Mac have 16GB of RAM?

**Comment by pozzoq** [comment]
I paste here the specs:

MacBook Pro 13" mid-2020
CPU: 2 GHz Intel Core i5 quad-core
Memory: 16 GB 3733 MHz LPDDR4X
Internal GPU: Intel Iris Plus Graphics 1536 MB
e-GPU: AMD Radeon 5500 XT with 4 Gb of Vram
